# Generated by Django 5.0.6 on 2024-05-30 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('jumlah_perubahan', models.IntegerField()),
                ('jenis_perubahan', models.CharField(max_length=10)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.weapon')),
            ],
        ),
    ]
